[package]
name = "swap"
version = "0.0.1"

[dependencies]
Sui = { git = "git@github.com:MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
swap = "0x0"
sui =  "0000000000000000000000000000000000000000000000000000000000000002"
zero = "0x0"
